### ISSUE TITLE
GeoRestrictedError

### ISSUE THREAD

**Issue by GFoley83** [dimkroon/itvx-for-kodi#102]
I'm not in the UK. I there any way around this natively? 
Besides using a VPN or changing the DNS on the router, which I'd love to be able to avoid.

**Comment by dimkroon** [comment]
No, circumventing GEO blocks is illegal. And would be very odd if ITVX first imposes a block and then creates a way around it, wouldn't it?

**Comment by GFoley83** [comment]
Wasn't aware it was illegal. Thank you for your informative, if slightly condescending answer.

**Comment by dimkroon** [comment]
Well, condescending or not, I would expect a person with a job description like yours to realise that a geo block cannot be bypassed natively.

**Comment by GFoley83** [comment]
Thanks for acknowledging. All is forgiven. Have a great day friend!

**Comment by dimkroon** [comment]
That was all totally unnecessary. Kindly refrain from commenting if you have nothing constructive to add.
