### ISSUE TITLE
Login/authentication fails with forbidden

### ISSUE THREAD

**Issue by nictjir** [dimkroon/itvx-for-kodi#103]
I can no longer authenticate.

https://auth.prd.user.itv.com/v2/auth
comes back with forbidden.

In testing, it looks like the header attribute
akamai-bm-telemetry
needs to be sent with the request now

akamai-bm-telemetry is a long string starting with &&& - I can't work out where this comes from though

**Comment by dimkroon** [comment]
Thanks for dropping a note!. 
Yes, that was my conclusion as well. That header had previously always been there, got ditched in one of the (many) recent changes at ITVX, but now it seems to be required again, along with some other changes.

**Comment by nictjir** [comment]
Indeed 1.4.1 fixes the issue - ingenious way to get the "telemetry" data
