### ISSUE TITLE
Search results limited to 10 items

### ISSUE THREAD

**Issue by BugfinderPro135** [dimkroon/itvx-for-kodi#111]
When you search for 'carry on' only 10 items get listed and there should be a lot more than that. (Carry On at Your Convenience is notably missing)

When you search for 'carry on at' 10 items are listed including this previously missing movie.

Can only assume there is some unmentioned search result limit that shouldn't really be there...

**Comment by dimkroon** [comment]
Thanks for reporting this issue
There is of course a limit to the number of search results.  ViwX just requests the default size, which was 24 items,  but apparently the default has been reduced to 10. I'll update viwx to request the same number as the website.

Note however, that quite recent tests showed that viwX's search is still suffering from #16, which can also influence the number of results.

**Comment by BugfinderPro135** [comment]
Would be great if you could add a way to be able to download stuff from itvx and save them as mp4 files...

**Comment by dimkroon** [comment]
> Would be great if you could add a way to be able to download stuff from itvx and save them as mp4 files...

This is in no way related to the issue discussed here. If you have a new problem or question, please create a new issue.
