### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by THGhost** [dimkroon/itvx-for-kodi#120]
How do you sign in? It asks for your user name, but ITVX doesn't give you a user name. You use your email address and a password to sign in there, but using my email address with viwx does not work.

**Comment by dimkroon** [comment]
Your username is your email address, so you did everything right.
Can you create a [debug log](https://kodi.wiki/view/Log_file) and post a link? 
Ensure to check the log and remove at least email and passwords before posting, but preferably also access and refresh tokens.

**Comment by dimkroon** [comment]
Never mind the log. I can replicate the issue and am working on a fix.

**Comment by dimkroon** [comment]
@THGhost: Could give branch adapt/login a go  and let me know if that works?

**Comment by dimkroon** [comment]
fixed in #121 released in viwX 1.5.2
