### ISSUE TITLE
Some programmes in catergories are listed as a single playable item.

### ISSUE THREAD

**Issue by dimkroon** [dimkroon/itvx-for-kodi#21]
Some items listed in categories are being shown as a single playable item, but are in fact programmes with multiple episodes.
As reported by gibxxi in [https://forum.kodi.tv/showthread.php?tid=369757&pid=3156431#pid3156431](https://forum.kodi.tv/showthread.php?tid=369757&pid=3156431#pid3156431)

**Comment by dimkroon** [comment]
In a category, playables were detected by checking field contentInfo. Items where that field represents a duration, or rather without the text 'series',  are regarded playable. This seems no longer valid. The majority of category items that have a duration appear to be programmes with multiple episodes. But not all.
Must find another way to reliably distinguish playables from programmes.

**Comment by dimkroon** [comment]
Most playable items appear to have empty encodedEpisodeId's. But still not all. Some of those may actually be programmes with just a single episode....
Most importantly, all items in category films have empty encodeEpisodeId's.

**Comment by gibxxi** [comment]
Hi dimkroon, just signing in to let you know I'm watching your progress with this issue. Good luck, and thanks for your efforts getting ITV-X up and running on kodi.

:)

Dan / Gib.

**Comment by dimkroon** [comment]
Now detecting playables by the absence of encodedEpisodeId. 
Which works OK for these playables,but leaves quite a number of programme folders that have only one episode. Some of them ar in fact programmes that originally did have more episodes, but only one being available. For others is it is perhaps a slight invonvenience.

Any way, this behaiour is consistent with that of a normal web browser and no epsiodes are hidden anymore.

**Comment by dimkroon** [comment]
Merges in development, will be in the upcomming release.

**Comment by gibxxi** [comment]
Many thanks for this @dimkroon.

Will test out the changes as and when I get the chance (A bit busy doing DIY ATM, lol). Any issues and i'll post them in the forum thread.

:)

Thanks again,

Dan / Gib.

**Comment by dimkroon** [comment]
@gibxxi 
Posting an issue on the forum is always OK, but don't hesitate to re-open this issue if you find it's not completely solved.

**Comment by gibxxi** [comment]
@dimkroon

Understood, will bear that in mind. Thanks again for your efforts with this.

Dan / Gib.
