### ISSUE TITLE
Premium content in search results is not hidden

### ISSUE THREAD

**Issue by Liqianyu** [dimkroon/itvx-for-kodi#34]
Even if "Hide Premium items" is enabled in the add-on settings, the search within the add-on will not hide Premium content.

**Comment by dimkroon** [comment]
ITVX's onlyFree filter on search was not stable. Producing results varying from no filtering at all to sometimes even returning the opposite of the filter.
The filter appears to be working OK for some time now. I re-enable setting "Hide Premium items" on search, which will be available in the upcoming version 1.2.0
