### ISSUE TITLE
No subtitles on live channels

### ISSUE THREAD

**Issue by TechnoCode44** [dimkroon/itvx-for-kodi#76]
When watching on any of the live channels with subtitles turned on, the subtitles won't appear. They work fine with on demand content (not live) and subtitles on the live channels work on itv.com.

**Comment by dimkroon** [comment]
Live subtitles are embedded in the live stream and are not affected by the add-on's settings. Contrary to VOD, you'll have to specifically enable subtitles in Kodi when watching the live stream; e.g. press 'T' on the keyboard, or use the on-screen menu while watching full screen.

I just checked and it worked all right. If the problem persists, please create a fresh debug log with libCurl logging enabled, upload it to some paste bin site and post a link here.

**Comment by TechnoCode44** [comment]
Apologizes for my ignorance. I thought that turning on subtitles for everything via the settings menu would work on the live channels.

**Comment by dimkroon** [comment]
I don't know of a way to force Kodi to use embedded subtitles - that's why this setting is in the section 'Catchup programs'. 
Embedded subs are handled by Inputstream Adaptive. Better ask there if you want to know more.
