### ISSUE TITLE
Provider Path Support

### ISSUE THREAD

**Issue by Jab2870** [dimkroon/itvx-for-kodi#84]
The youtube plugin I use on kodi registers paths such as /play/ that allow for content to be selected on another device and sent to the kodi box to play.

https://github.com/anxdpanic/plugin.video.youtube/blob/01653e468a02e537cf1531491468667ff5d00529/resources/lib/youtube_plugin/youtube/provider.py#L604

This allows me to run a kodi rpc command for Player.Open with `plugin://plugin.video.youtube/play/?video_id={whatever}`

It would be extremely useful if I could do the same for this addon. For instance, if I ran Player.Open with `plugin://plugin.video.viewx/play/video_id=2a4885`, it would open https://www.itv.com/watch/spy-kids/2a4885 using this plugin.

**Comment by dimkroon** [comment]
I don't think there is such a thing as 'registering' an path at Kodi to allow it to be used in JSONRPC. Kodi uses URL like arguments when it invokes a plugin and you can use the same (or similar) URLs in JSONRPC.

I'm not familiar with the youtube addon, but from the link you provided it looks like it's just registering a callback function to it's own internal router logic. Viwx uses codequick for routing (and other purposes) and requires URLs in a slightly different format. The format for viwX is the full path to the function from the base directory of the plugin, with function arguments as query string (url encoded of course).

For the episode you mentioned it should be something like:
`plugin://plugin.video.viwx/resources/lib/main/play_title/?url=%2Fwatch%2Fspy-kids%2F2a4885`, but I haven't tested it.

**Comment by Jab2870** [comment]
That works. Thanks very much.
